import type { Metadata } from 'next';
import { Roboto_Slab } from 'next/font/google';
import './globals.css';

const robotoSlab = Roboto_Slab({
  variable: '--font-roboto-slab',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSlab.variable} antialiased w-dvw min-h-dvh font-roboto-slab @container`}>{children}</body>
    </html>
  );
}
